
#salesforce connection credentials
salesforce:
 username: "![LdMnKDvvxRudlQCwX4HRx6ormDDhDqyXWFPgGcTSzpA=]"
 password: "![oLzr6khpZ4MX7TtMXABJzA==]"
 securitytoken: "![AnuM9OTutlf1Z7B7mQFXAumVBnhL27m5ovMnZUd/oQM=]"
 