#%RAML 1.0 SecurityScheme
type: x-client-credentials
description: |
    Client credentials security scheme for authenticating requests triggerd by consumers within organisation.
describedBy:
  headers:
    client_id:
      type: string
      example: "7b404180fbb84b099179a4126a9576ff"
    client_secret:
      type: string
      example: "e241f4aa3eca4b2a8FA67A2FEF5754F8"
  